import { ThreatLevel } from '../../types';
import { RiskClassification } from '../risk/riskConfig';
import { DetectorResult } from '../../pipeline/types';

export interface ExplanationSignalItem {
  signal: string;
  detail: string;
  severity: 'low' | 'medium' | 'high' | 'critical';
  source_detector?: string;
}

export interface ExplanationScamType {
  category: string;
  name: string;
  description: string;
  threat_level: string;
}

export interface ExplanationUncertainty {
  is_uncertain: boolean;
  reason: string;
  missing_information: string[];
  confidence_level: 'very_low' | 'low' | 'medium' | 'high' | 'verified';
}

export interface AiStructuredExplanation {
  // 1. Why the content is suspicious
  why_suspicious: string;

  // 2. Which signals triggered the detection
  triggered_signals: ExplanationSignalItem[];

  // 3. What type of scam may be involved
  scam_type: ExplanationScamType;

  // 4. What the user should do
  actionable_advice: string[];

  // 5. What uncertainty remains
  uncertainty_notes: ExplanationUncertainty;

  // Grounding & Verification Metadata (guarantees no fabricated evidence)
  grounded_in_evidence: boolean;
  evidence_summary: string;
  verified_signal_count: number;
  unverified_claims_filtered: number;

  // Backward-compatible summary and actions
  summary: string;
  aiExplanation: string;
  recommended_actions: string[];
  /** Alias for recommended_actions — used by frontend display layer */
  recommendedActions?: string[];
  safe_factors: string[];

  // Engine provenance — 'ai_model' when Gemini generated the narrative, 'grounded_rules_engine' as fallback
  generated_by: 'ai_model' | 'grounded_rules_engine';
  /** True when the narrative was generated by a live LLM call, false when rules engine was used */
  ai_generated: boolean;
  engine_version: string;
  timestamp: string;
}

export interface ExplanationContext {
  scanId?: string;
  targetType: 'TEXT' | 'URL' | 'FILE' | 'QR';
  threatCategory: string;
  riskScore: number;
  classification?: RiskClassification;
  threatLevel?: ThreatLevel;
  confidenceScore?: number;
  language?: 'en' | 'km' | 'km-en' | 'unknown';
  indicators: string[];
  detectorResults?: DetectorResult[];
  rawContentSnippet?: string;
  evidenceBreakdown?: Record<string, number>;
}
