import React, { useState } from 'react';
import {
  ShieldAlert,
  ShieldCheck,
  AlertTriangle,
  Info,
  Clock,
  ChevronDown,
  ChevronUp,
  Terminal,
  Sparkles,
  HelpCircle,
  ThumbsUp,
  ThumbsDown,
  Check,
  Tag,
} from 'lucide-react';
import type { AnalysisResult, Language } from '../../types';
import { translations } from '../../i18n/translations';
import { RiskScore } from './RiskScore';
import { DetectionReasons } from './DetectionReasons';
import { RecommendedAction } from './RecommendedAction';
import { AiExplanationPanel } from './AiExplanationPanel';
import { api } from '../../services/api';

interface ResultCardProps {
  result: AnalysisResult;
  onReset: () => void;
  onReportScam: () => void;
  lang: Language;
}

export const ResultCard: React.FC<ResultCardProps> = ({
  result,
  onReset,
  onReportScam,
  lang,
}) => {
  const t = translations[lang];
  const [isCopied, setIsCopied] = useState(false);
  const [showTechnicalDetails, setShowTechnicalDetails] = useState(false);

  // User feedback states
  const [feedbackSubmitted, setFeedbackSubmitted] = useState(false);
  const [showFeedbackCorrection, setShowFeedbackCorrection] = useState(false);
  const [selectedCorrectionCategory, setSelectedCorrectionCategory] = useState('PHISHING');
  const [feedbackComments, setFeedbackComments] = useState('');

  const handleCopyReport = () => {
    const reportText = `[ScamCheck AI Security & Threat Report]
Status: ${result.riskLevel.toUpperCase()} (Risk Score: ${result.riskScore}/100)
Category: ${result.threatCategory || 'General Threat'}
Assessment: ${result.title}
Summary: ${result.summary}
Key Signals Detected:
${result.signals.map((s) => `- ${s.title}: ${s.description}`).join('\n')}
Recommended Actions:
${result.recommendedActions.map((a) => `- ${a}`).join('\n')}
Confidence: ${result.confidenceScore}%
Analyzed at: ${result.timestamp}
Generated by ScamCheck AI`;

    navigator.clipboard.writeText(reportText).then(() => {
      setIsCopied(true);
      setTimeout(() => setIsCopied(false), 3000);
    });
  };

  const handleExportJson = () => {
    const jsonString = `data:text/json;charset=utf-8,${encodeURIComponent(JSON.stringify(result, null, 2))}`;
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute('href', jsonString);
    downloadAnchor.setAttribute('download', `scamcheck-forensics-${result.id || Date.now()}.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  const handleFeedbackSubmit = async (isCorrect: boolean) => {
    try {
      await api.submitFeedback({
        scanId: result.id,
        isCorrect,
        suggestedCategory: isCorrect ? undefined : selectedCorrectionCategory,
        comments: feedbackComments || undefined,
      });
      setFeedbackSubmitted(true);
      setShowFeedbackCorrection(false);
    } catch {
      setFeedbackSubmitted(true);
    }
  };

  // Status icon & style
  let statusBg = 'bg-safe-light/50 border-safe-border';
  let statusIcon = <ShieldCheck className="w-7 h-7 text-safe flex-shrink-0" />;
  if (result.riskLevel === 'high_risk') {
    statusBg = 'bg-danger-light/50 border-danger-border';
    statusIcon = <ShieldAlert className="w-7 h-7 text-danger flex-shrink-0" />;
  } else if (result.riskLevel === 'suspicious') {
    statusBg = 'bg-suspicious-light/50 border-suspicious-border';
    statusIcon = <AlertTriangle className="w-7 h-7 text-suspicious flex-shrink-0" />;
  }

  const categoryLabel = result.threatCategory
    ? (t.threatCategories as Record<string, string>)[result.threatCategory] || result.threatCategory
    : undefined;

  return (
    <div className="space-y-5 animate-fadeIn">
      {/* Primary Classification Banner */}
      <div className={`p-4 sm:p-5 rounded-xl border ${statusBg} flex items-start gap-4`}>
        {statusIcon}
        <div className="space-y-1.5 flex-1">
          <div className="flex items-center justify-between gap-2 flex-wrap">
            <h2 className="text-lg sm:text-xl font-bold text-typography-headline">
              {result.title}
            </h2>
            <div className="flex items-center gap-1.5 flex-wrap">
              {categoryLabel && (
                <span className="text-[10px] font-bold uppercase tracking-wider px-2 py-0.5 rounded-full bg-primary/10 text-primary border border-primary/20 flex items-center gap-1">
                  <Tag className="w-3 h-3" />
                  <span>{categoryLabel}</span>
                </span>
              )}
              <span className="text-[11px] font-mono text-typography-muted flex items-center gap-1 bg-white/70 px-2 py-0.5 rounded-full border border-black/5">
                <Clock className="w-3 h-3" />
                <span>{result.timestamp}</span>
              </span>
            </div>
          </div>
          <p className="text-xs sm:text-sm text-typography-body leading-relaxed">
            {result.summary}
          </p>
        </div>
      </div>

      {/* AI Explanation — Full 5-Part Structured Panel */}
      {result.structuredExplanation ? (
        <AiExplanationPanel explanation={result.structuredExplanation} />
      ) : result.aiExplanation ? (
        // Fallback: compact callout for legacy / fallback code paths
        <div className="p-3.5 rounded-xl bg-primary-light/40 border border-primary/20 text-xs text-typography-body flex items-start gap-2.5">
          <Sparkles className="w-4 h-4 text-primary flex-shrink-0 mt-0.5" />
          <div>
            <span className="font-semibold text-primary block mb-0.5">AI Security Explanation</span>
            <p className="leading-relaxed text-[11px] sm:text-xs">{result.aiExplanation}</p>
          </div>
        </div>
      ) : null}

      {/* Input Snippet Reference */}
      <div className="p-3 rounded-lg bg-surfaceInput text-xs border border-borderDefault">
        <span className="text-[11px] font-semibold text-typography-muted uppercase tracking-wider block mb-1">
          Analyzed Content Preview:
        </span>
        <p className="font-mono text-typography-body truncate">
          "{result.inputSnippet}"
        </p>
      </div>

      {/* Numerical Risk Score Gauge */}
      <RiskScore
        score={result.riskScore}
        riskLevel={result.riskLevel}
        lang={lang}
      />

      {/* Transparent Multi-Factor Evidence Weighting */}
      {result.evidenceBreakdown && (
        <div className="p-4 rounded-xl border border-borderDefault bg-card/70 space-y-2.5">
          <span className="text-xs font-bold text-typography-headline uppercase tracking-wider block">
            {t.evidenceBreakdown.title}
          </span>
          <div className="space-y-2 text-xs">
            <div>
              <div className="flex justify-between text-[11px] mb-1 text-typography-muted">
                <span>{t.evidenceBreakdown.message}</span>
                <span className="font-mono font-semibold">{result.evidenceBreakdown.message_analysis_score}%</span>
              </div>
              <div className="w-full bg-surfaceInput rounded-full h-1.5 overflow-hidden">
                <div
                  className="bg-primary h-1.5 rounded-full transition-all duration-500"
                  style={{ width: `${result.evidenceBreakdown.message_analysis_score}%` }}
                />
              </div>
            </div>
            <div>
              <div className="flex justify-between text-[11px] mb-1 text-typography-muted">
                <span>{t.evidenceBreakdown.url}</span>
                <span className="font-mono font-semibold">{result.evidenceBreakdown.url_analysis_score}%</span>
              </div>
              <div className="w-full bg-surfaceInput rounded-full h-1.5 overflow-hidden">
                <div
                  className="bg-primary h-1.5 rounded-full transition-all duration-500"
                  style={{ width: `${result.evidenceBreakdown.url_analysis_score}%` }}
                />
              </div>
            </div>
            <div>
              <div className="flex justify-between text-[11px] mb-1 text-typography-muted">
                <span>{t.evidenceBreakdown.indicators}</span>
                <span className="font-mono font-semibold">{result.evidenceBreakdown.threat_indicators_score}%</span>
              </div>
              <div className="w-full bg-surfaceInput rounded-full h-1.5 overflow-hidden">
                <div
                  className="bg-danger h-1.5 rounded-full transition-all duration-500"
                  style={{ width: `${result.evidenceBreakdown.threat_indicators_score}%` }}
                />
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Reasons & Signals Flagged */}
      <DetectionReasons
        signals={result.signals}
        safeFactors={result.details.safeFactors}
        riskLevel={result.riskLevel}
        lang={lang}
      />

      {/* User Verification / Feedback Loop */}
      <div className="p-4 rounded-xl border border-borderDefault bg-card/60 space-y-3 text-xs">
        <div className="flex items-center justify-between flex-wrap gap-2">
          <span className="font-semibold text-typography-headline flex items-center gap-1.5">
            <HelpCircle className="w-4 h-4 text-primary" />
            <span>{t.feedback.prompt}</span>
          </span>
          {feedbackSubmitted ? (
            <span className="inline-flex items-center gap-1 text-safe font-semibold text-xs">
              <Check className="w-3.5 h-3.5" />
              <span>{t.feedback.submitted}</span>
            </span>
          ) : (
            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={() => handleFeedbackSubmit(true)}
                className="px-3 py-1 rounded-lg bg-surfaceInput hover:bg-safe-light/50 border border-borderDefault hover:border-safe text-typography-body hover:text-safe-dark font-medium transition-standard cursor-pointer flex items-center gap-1"
              >
                <ThumbsUp className="w-3 h-3 text-safe" />
                <span>{t.feedback.yes}</span>
              </button>
              <button
                type="button"
                onClick={() => setShowFeedbackCorrection(!showFeedbackCorrection)}
                className="px-3 py-1 rounded-lg bg-surfaceInput hover:bg-danger-light/50 border border-borderDefault hover:border-danger text-typography-body hover:text-danger font-medium transition-standard cursor-pointer flex items-center gap-1"
              >
                <ThumbsDown className="w-3 h-3 text-danger" />
                <span>{t.feedback.no}</span>
              </button>
            </div>
          )}
        </div>

        {/* Correction selector */}
        {showFeedbackCorrection && !feedbackSubmitted && (
          <div className="pt-2 border-t border-borderDefault space-y-2.5 animate-fadeIn">
            <label className="text-[11px] font-semibold text-typography-muted block">
              {t.feedback.whatCorrect}
            </label>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-1.5">
              {[
                'SAFE',
                'PHISHING',
                'JOB_SCAM',
                'INVESTMENT_SCAM',
                'PAYMENT_SCAM',
                'PRIZE_SCAM',
                'MALWARE',
                'OTHER',
              ].map((cat) => (
                <button
                  key={cat}
                  type="button"
                  onClick={() => setSelectedCorrectionCategory(cat)}
                  className={`px-2 py-1.5 rounded text-[10px] font-mono border transition-standard cursor-pointer ${
                    selectedCorrectionCategory === cat
                      ? 'bg-primary text-white border-primary font-bold'
                      : 'bg-surfaceInput border-borderDefault text-typography-body hover:border-primary/40'
                  }`}
                >
                  {cat.replace('_', ' ')}
                </button>
              ))}
            </div>
            <textarea
              value={feedbackComments}
              onChange={(e) => setFeedbackComments(e.target.value)}
              placeholder="Optional notes for our cybersecurity analysts..."
              rows={2}
              className="w-full p-2 text-xs rounded-lg bg-surfaceInput border border-borderDefault focus:border-primary outline-none"
            />
            <button
              type="button"
              onClick={() => handleFeedbackSubmit(false)}
              className="w-full h-8 rounded-lg bg-primary text-white text-xs font-semibold hover:bg-primary-hover transition-standard cursor-pointer"
            >
              {t.feedback.submit}
            </button>
          </div>
        )}
      </div>

      {/* Technical Forensics Inspector Accordion */}
      <div className="border border-borderDefault rounded-xl overflow-hidden bg-card/60">
        <button
          type="button"
          onClick={() => setShowTechnicalDetails(!showTechnicalDetails)}
          className="w-full px-4 py-3 flex items-center justify-between text-xs font-semibold text-typography-body hover:bg-surfaceInput/60 transition-standard cursor-pointer"
        >
          <span className="flex items-center gap-2">
            <Terminal className="w-4 h-4 text-primary" />
            <span>{showTechnicalDetails ? t.actions.hideDetails : t.actions.viewDetails}</span>
            <span className="px-1.5 py-0.5 rounded text-[10px] font-mono bg-surfaceInput border border-borderDefault text-typography-muted">
              {result.details?.indicatorsFound ?? result.signals.length} signals
            </span>
          </span>
          {showTechnicalDetails ? (
            <ChevronUp className="w-4 h-4 text-typography-muted" />
          ) : (
            <ChevronDown className="w-4 h-4 text-typography-muted" />
          )}
        </button>

        {showTechnicalDetails && (
          <div className="p-4 border-t border-borderDefault bg-surfaceInput/30 space-y-3 text-xs">
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
              <div className="p-2 rounded bg-card border border-borderDefault">
                <span className="text-[10px] text-typography-muted uppercase tracking-wider block">Scan Mode</span>
                <span className="font-mono font-medium text-typography-headline uppercase">{result.mode}</span>
              </div>
              <div className="p-2 rounded bg-card border border-borderDefault">
                <span className="text-[10px] text-typography-muted uppercase tracking-wider block">Indicators</span>
                <span className="font-mono font-medium text-typography-headline">
                  {result.details?.indicatorsFound ?? result.signals.length} flagged
                </span>
              </div>
              <div className="p-2 rounded bg-card border border-borderDefault">
                <span className="text-[10px] text-typography-muted uppercase tracking-wider block">Confidence</span>
                <span className="font-mono font-medium text-typography-headline">{result.confidenceScore}%</span>
              </div>
              <div className="p-2 rounded bg-card border border-borderDefault">
                <span className="text-[10px] text-typography-muted uppercase tracking-wider block">Category</span>
                <span className="font-mono font-medium text-typography-headline truncate block">
                  {result.threatCategory || 'N/A'}
                </span>
              </div>
            </div>

            {/* Target Metadata if available */}
            {(result.details?.domainEvaluated || result.details?.fileName || result.details?.qrPayload) && (
              <div className="p-2.5 rounded bg-card border border-borderDefault space-y-1">
                <span className="text-[10px] text-typography-muted uppercase tracking-wider block">Evaluated Target / QR Payload</span>
                <p className="font-mono text-xs text-typography-headline break-all">
                  {result.details.qrPayload || result.details.domainEvaluated || result.details.fileName}
                  {result.details.fileSize && (
                    <span className="text-typography-muted ml-2">({result.details.fileSize})</span>
                  )}
                </p>
              </div>
            )}

            {/* Raw Forensics JSON View */}
            <div className="space-y-1">
              <span className="text-[10px] text-typography-muted uppercase tracking-wider block">Forensic Metadata Payload</span>
              <pre className="p-3 rounded-lg bg-black/90 text-emerald-400 font-mono text-[11px] overflow-x-auto max-h-48 leading-relaxed border border-borderDefault">
                {JSON.stringify(
                  {
                    id: result.id,
                    mode: result.mode,
                    threatCategory: result.threatCategory,
                    riskLevel: result.riskLevel,
                    riskScore: result.riskScore,
                    confidenceScore: result.confidenceScore,
                    timestamp: result.timestamp,
                    evidenceBreakdown: result.evidenceBreakdown,
                    details: result.details,
                    signalsCount: result.signals.length,
                  },
                  null,
                  2
                )}
              </pre>
            </div>
          </div>
        )}
      </div>

      {/* Recommended Action & Action CTAs */}
      <RecommendedAction
        riskLevel={result.riskLevel}
        recommendations={result.recommendedActions}
        onReset={onReset}
        onCopyReport={handleCopyReport}
        onExportJson={handleExportJson}
        onReportScam={onReportScam}
        isCopied={isCopied}
        lang={lang}
      />

      {/* Confidence & Advisory Disclaimer (Principle 21 & 25) */}
      <div className="pt-3 border-t border-borderDefault flex flex-col sm:flex-row items-start sm:items-center justify-between gap-2 text-[11px] text-typography-muted">
        <div className="flex items-center gap-1.5">
          <Info className="w-3.5 h-3.5 text-primary flex-shrink-0" />
          <span>{t.results.confidence}: <strong className="text-typography-headline font-mono">{result.confidenceScore}%</strong></span>
        </div>
        <p className="italic text-[10px] sm:text-right max-w-sm">
          {t.results.advisoryNotice}
        </p>
      </div>
    </div>
  );
};
